# Generated by Django 3.2.7 on 2021-09-13 19:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_state_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('date_started', models.DateField(default=django.utils.timezone.now, help_text='Tenure start date', verbose_name='Start year')),
                ('date_ended', models.DateField(default=django.utils.timezone.now, help_text='Tenure end date', verbose_name='End year')),
                ('is_current', models.BooleanField(default=False, help_text='Currently active as Governor?', verbose_name='Current governor')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governors', to='states.state', verbose_name='State')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
