# Generated by Django 3.2.7 on 2021-09-14 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0004_governor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(help_text='State city belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='states.state'),
        ),
        migrations.AlterField(
            model_name='governor',
            name='state',
            field=models.ForeignKey(help_text='State governing', on_delete=django.db.models.deletion.PROTECT, related_name='governors', to='states.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='localgovernmentarea',
            name='short_code',
            field=models.CharField(db_index=True, help_text='Three characters unique identifier of lga', max_length=3, unique=True, verbose_name='Short code'),
        ),
        migrations.AlterField(
            model_name='localgovernmentarea',
            name='state',
            field=models.ForeignKey(help_text='State LGA belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='states.state'),
        ),
        migrations.AlterField(
            model_name='localgovernmentarea',
            name='zip_code',
            field=models.CharField(blank=True, db_index=True, help_text='Zipcode for LGA', max_length=6, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='state',
            name='capital',
            field=models.CharField(db_index=True, help_text='Capital of state', max_length=255, unique=True, verbose_name='capital'),
        ),
        migrations.AlterField(
            model_name='state',
            name='short_code',
            field=models.CharField(db_index=True, help_text='Two SHORT CODE to identify a state', max_length=3, unique=True, verbose_name='Short Code'),
        ),
        migrations.AlterField(
            model_name='state',
            name='slogan',
            field=models.CharField(help_text='Slogan for state', max_length=255, verbose_name='slogan'),
        ),
        migrations.AlterField(
            model_name='state',
            name='website',
            field=models.URLField(blank=True, help_text='Official website of state', null=True, verbose_name='Website'),
        ),
    ]
