spectaql:
  logoFile: ./src/static/statesng/ng.png
  faviconFile: ./src/static/favicon/favicon.ico

introspection:
  schemaFile: ./src/statesngapps/apis/graphql/states/schemas/gqls/schema.gql

info:
  title: GraphQL API Reference
  description: Welcome to the party!
  termsOfService: https://www.example.com/terms
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: 127.0.0.1/graphql
    description: Production
    production: false
