# Generated by Django 3.2.8 on 2021-10-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('flatpages.flatpage',),
        ),
    ]
