# Generated by Django 3.2.8 on 2021-10-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_device_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
