# Generated by Django 3.2.8 on 2021-10-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
