# Generated by Django 3.2.8 on 2021-10-20 18:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Governor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('government', models.CharField(choices=[('military', 'Military'), ('democracy', 'Democracy')], help_text='System of government', max_length=10, null=True, verbose_name='government type')),
                ('date_started', models.DateField(default=django.utils.timezone.now, help_text='Tenure start date', verbose_name='Start year')),
                ('date_ended', models.DateField(default=django.utils.timezone.now, help_text='Tenure end date', verbose_name='End year')),
                ('is_current', models.BooleanField(default=False, help_text='Currently active as Governor?', verbose_name='Current governor')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalGovernmentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('short_code', models.CharField(blank=True, db_index=True, help_text='Three characters unique identifier of LGA', max_length=3, verbose_name='Short code')),
                ('zip_code', models.CharField(blank=True, db_index=True, help_text='Zipcode for LGA', max_length=6, verbose_name='Zip Code')),
                ('secretariat', models.TextField(blank=True, help_text='Secretariat address of LGA')),
            ],
            options={
                'verbose_name': 'Local Government Area',
                'verbose_name_plural': 'Local Government Areas',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('capital', models.CharField(db_index=True, help_text='Capital of state', max_length=255, unique=True, verbose_name='capital')),
                ('slogan', models.CharField(help_text='Slogan for state', max_length=255, verbose_name='slogan')),
                ('short_code', models.CharField(db_index=True, help_text='Two SHORT CODE to identify a state', max_length=3, unique=True, verbose_name='Short Code')),
                ('geo_zone', models.CharField(blank=True, choices=[('nc', 'North central'), ('ne', 'North east'), ('nw', 'North west'), ('se', 'South south'), ('ss', 'South south'), ('sw', 'South south')], help_text='Geo political zone of state', max_length=2, verbose_name='Geo political zone')),
                ('website', models.URLField(blank=True, help_text='Official website of state', null=True, verbose_name='Website')),
                ('map', models.ImageField(blank=True, help_text='Map of the state', upload_to='states', verbose_name='State map')),
                ('postal_code', models.CharField(blank=True, default='000001', help_text='Postal Code to find state', max_length=6, verbose_name='Postal code')),
                ('creation_date', models.DateField(default=django.utils.timezone.now, help_text='Date state was created', verbose_name='Creation date')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('name', 'postal_code'), name='unique_name_on_postal_code'),
        ),
        migrations.AddField(
            model_name='localgovernmentarea',
            name='state',
            field=models.ForeignKey(help_text='State LGA belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='localgovernmentareas', to='states.state'),
        ),
        migrations.AddField(
            model_name='governor',
            name='state',
            field=models.ForeignKey(help_text='State governing', on_delete=django.db.models.deletion.PROTECT, related_name='governors', to='states.state', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='district',
            name='lga',
            field=models.ForeignKey(help_text='LGA district falls under', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='states.localgovernmentarea'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(help_text='State city belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='states.state'),
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
            ],
            options={
                'verbose_name': 'LGA',
                'verbose_name_plural': 'LGAs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('states.localgovernmentarea',),
        ),
        migrations.AddConstraint(
            model_name='localgovernmentarea',
            constraint=models.UniqueConstraint(fields=('state', 'name'), name='unique_lga_name_and_state'),
        ),
        migrations.AddConstraint(
            model_name='localgovernmentarea',
            constraint=models.UniqueConstraint(fields=('state', 'short_code'), name='unique_lga_shrt_code_and_state'),
        ),
    ]
