# Generated by Django 3.2.7 on 2021-09-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('capital', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='capital')),
                ('slogan', models.CharField(max_length=255, verbose_name='slogan')),
                ('short_code', models.CharField(db_index=True, max_length=3, unique=True, verbose_name='Short Code')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalGovernmentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('short_code', models.CharField(db_index=True, max_length=3, unique=True, verbose_name='Short code')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='states.state')),
            ],
            options={
                'verbose_name': 'Local Government Area',
                'verbose_name_plural': 'Local Government Areas',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='states.state')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
            ],
            options={
                'verbose_name': 'LGA',
                'verbose_name_plural': 'LGAs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('states.localgovernmentarea',),
        ),
        migrations.AddConstraint(
            model_name='localgovernmentarea',
            constraint=models.UniqueConstraint(fields=('state', 'name'), name='unique_lga_name_and_state'),
        ),
    ]
