# Generated by Django 3.2.7 on 2021-09-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localgovernmentarea',
            name='zip_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, verbose_name='Zip Code'),
        ),
    ]
