# Generated by Django 3.2.7 on 2021-09-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0002_localgovernmentarea_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
