# Generated by Django 3.2.8 on 2021-10-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0002_state_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='governor',
            name='government',
            field=models.CharField(choices=[('military', 'military'), ('democracy', 'democracy')], help_text='System of government', max_length=10, null=True, verbose_name='government type'),
        ),
    ]
