# Generated by Django 3.2.8 on 2021-10-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0002_remove_state_geo_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='geo_zone',
            field=models.CharField(blank=True, choices=[('nc', 'North central'), ('ne', 'North east'), ('nw', 'North west'), ('se', 'South south'), ('ss', 'South south'), ('sw', 'South south')], help_text='Geo political zone of state', max_length=2, verbose_name='Geo political zone'),
        ),
    ]
