# Generated by Django 3.2.8 on 2021-10-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_governor_government'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governor',
            name='government',
            field=models.CharField(choices=[('military', 'Military'), ('democracy', 'Democracy')], help_text='System of government', max_length=10, null=True, verbose_name='government type'),
        ),
    ]
