# Generated by Django 3.2.8 on 2021-10-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0004_alter_state_geo_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='geo_zone',
            field=models.CharField(choices=[('nc', 'North central'), ('ne', 'North east'), ('nw', 'North west'), ('se', 'South east'), ('ss', 'South south'), ('sw', 'South west')], help_text='Geo political zone of state', max_length=2, verbose_name='Geo political zone'),
        ),
    ]
