# Generated by Django 3.2.8 on 2021-10-16 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0004_alter_governor_government'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localgovernmentarea',
            name='state',
            field=models.ForeignKey(help_text='State LGA belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='localgovernmentareas', to='states.state'),
        ),
    ]
