# Generated by Django 3.2.8 on 2021-10-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0006_alter_localgovernmentarea_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localgovernmentarea',
            name='short_code',
            field=models.CharField(blank=True, db_index=True, help_text='Three characters unique identifier of LGA', max_length=3, verbose_name='Short code'),
        ),
    ]
