# Generated by Django 3.2.8 on 2021-10-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0007_alter_localgovernmentarea_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='localgovernmentarea',
            name='secretariat',
            field=models.TextField(blank=True, help_text='Secretariat address of LGA'),
        ),
    ]
