# Generated by Django 3.2.8 on 2021-10-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0010_tryingcon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TryingCon',
        ),
    ]
